/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CreationSiteArtisteRouteImport } from './routes/creation-site-artiste'
import { Route as SiteHumoristeRouteImport } from './routes/site-humoriste'
import { Route as SiteSortieFilmRouteImport } from './routes/site-sortie-film'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as EtudesSlugRouteImport } from './routes/etudes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationSiteArtisteRoute = CreationSiteArtisteRouteImport.update({
  id: '/creation-site-artiste',
  path: '/creation-site-artiste',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteHumoristeRoute = SiteHumoristeRouteImport.update({
  id: '/site-humoriste',
  path: '/site-humoriste',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSortieFilmRoute = SiteSortieFilmRouteImport.update({
  id: '/site-sortie-film',
  path: '/site-sortie-film',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudesSlugRoute = EtudesSlugRouteImport.update({
  id: '/etudes/$slug',
  path: '/etudes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creation-site-artiste': typeof CreationSiteArtisteRoute
  '/site-humoriste': typeof SiteHumoristeRoute
  '/site-sortie-film': typeof SiteSortieFilmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/etudes/$slug': typeof EtudesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creation-site-artiste': typeof CreationSiteArtisteRoute
  '/site-humoriste': typeof SiteHumoristeRoute
  '/site-sortie-film': typeof SiteSortieFilmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/etudes/$slug': typeof EtudesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/creation-site-artiste': typeof CreationSiteArtisteRoute
  '/site-humoriste': typeof SiteHumoristeRoute
  '/site-sortie-film': typeof SiteSortieFilmRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/etudes/$slug': typeof EtudesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/creation-site-artiste'
    | '/site-humoriste'
    | '/site-sortie-film'
    | '/sitemap.xml'
    | '/etudes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/creation-site-artiste'
    | '/site-humoriste'
    | '/site-sortie-film'
    | '/sitemap.xml'
    | '/etudes/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/creation-site-artiste'
    | '/site-humoriste'
    | '/site-sortie-film'
    | '/sitemap.xml'
    | '/etudes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CreationSiteArtisteRoute: typeof CreationSiteArtisteRoute
  SiteHumoristeRoute: typeof SiteHumoristeRoute
  SiteSortieFilmRoute: typeof SiteSortieFilmRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EtudesSlugRoute: typeof EtudesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creation-site-artiste': {
      id: '/creation-site-artiste'
      path: '/creation-site-artiste'
      fullPath: '/creation-site-artiste'
      preLoaderRoute: typeof CreationSiteArtisteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-humoriste': {
      id: '/site-humoriste'
      path: '/site-humoriste'
      fullPath: '/site-humoriste'
      preLoaderRoute: typeof SiteHumoristeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-sortie-film': {
      id: '/site-sortie-film'
      path: '/site-sortie-film'
      fullPath: '/site-sortie-film'
      preLoaderRoute: typeof SiteSortieFilmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etudes/$slug': {
      id: '/etudes/$slug'
      path: '/etudes/$slug'
      fullPath: '/etudes/$slug'
      preLoaderRoute: typeof EtudesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CreationSiteArtisteRoute: CreationSiteArtisteRoute,
  SiteHumoristeRoute: SiteHumoristeRoute,
  SiteSortieFilmRoute: SiteSortieFilmRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EtudesSlugRoute: EtudesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
